### ISSUE TITLE
4.7 focuses on high contrast solutions

### ISSUE THREAD

**Issue by dpersing** [w3c/apa#100]
I wonder if 4.7 could be expanded to include color customizations that aren't just in high contrast. Many users could benefit from color customization but may prefer to not rely on a high contrast solution specifically.

**Comment by sehollier** [comment]
Thank you for your comment. This was discussed in the RQTF meeting. The provision of high contrast is in relation to the colour contrast ratio and is not limited to any particular combination. For example, a high contrast theme could be black-on-white or yellow-on-blue. As such,, the group has decided to leave this point unchanged as the reference to high contrast here allows for colour customisations
