### ISSUE TITLE
Additional problems with CAPTCHA

### ISSUE THREAD

**Issue by gianwild** [w3c/apa#13]
Hi

We did an audit on Google's reCAPTCHA in June 2018. I have attached the results.
[CAPTCHA errors.docx](https://github.com/w3c/apa/files/2878115/CAPTCHA.errors.docx).

Not sure if this is helpful. Happy to discuss.

Gian

**Comment by JaninaSajka** [comment]
Hi, Gian:

Thanks for forwarding your report.

You, and another commentor raise a valid point regarding WCAG and
CAPTCHA. We have addressed this in two ways in this branch:

https://raw.githack.com/w3c/apa/wcag-captcha/captcha/index.html


1.)	We have said more in our Introduction section, pointing out that
it is important to conform to WCAG--that the exemption for CAPTCHA in
WCAG is only for the content of the CAPTCHA.

2.)	We have noted the reporting of reCAPTCHA failing WCAG in the
reCAPTCHA section.

Further comments most welcome.

Best,

Janina

gianwild writes:
> Hi
> 
> We did an audit on Google's reCAPTCHA in June 2018. I have attached the results.
> [CAPTCHA errors.docx](https://github.com/w3c/apa/files/2878115/CAPTCHA.errors.docx).
> 
> Not sure if this is helpful. Happy to discuss.
> 
> Gian
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/apa/issues/13

-- 

Janina Sajka

Linux Foundation Fellow
Executive Chair, Accessibility Workgroup:	http://a11y.org

The World Wide Web Consortium (W3C), Web Accessibility Initiative (WAI)
Chair, Accessible Platform Architectures	http://www.w3.org/wai/apa

**Comment by gianwild** [comment]
Thanks!

Cheers,
Gian

**Comment by gianwild** [comment]
Thanks Janina. I noted a typo in the reCAPTCHA section: “amounts” instead of “amounts”

Cheers,
Gian
