### ISSUE TITLE
Interactions between Natural Language Interfaces and other user interfaces

### ISSUE THREAD

**Issue by RealJoshue108** [w3c/apa#143]
This should be included in the document. How will this work?

**Comment by jasonjgw** [comment]
I can try to draft a need/requirement based on John's suggestion about not expecting the user to switch input or output modes during an interaction. This may not address the entire issue (depending on what we understand the issue to be), but it would address part of it.

**Comment by jasonjgw** [comment]
I created Pull Request 144 with a draft of this idea, with naur as the base branch.

**Comment by RealJoshue108** [comment]
Added to main - closing https://raw.githack.com/w3c/apa/main/naur/index.html#means-of-input-and-output
