### ISSUE TITLE
first impresion

### ISSUE THREAD

**Issue by lseeman** [w3c/apa#147]
Hi
I think cognitive overload, reliance on memory (routs etc), knowing what things, ability to have support are all things that can affect XR (in https://raw.githack.com/w3c/apa/6d5bf713d9d7c65ecda104c213ad47b0e98cfbe1/xaur/index.html)
Sensory oveload can also be a problem. (from the two or three times i have tried it)

I think there are also many mental health risks such as panics and triggers, but this is not my field.
 I will ask coga to review it

**Comment by RealJoshue108** [comment]
We are currently getting welcome feedback from COGA - closing issue
