### ISSUE TITLE
REQ 11a: Allow the user to set a 'safe place' - quick key, shortcut or macro.

### ISSUE THREAD

**Issue by lseeman** [w3c/apa#149]
This does seem usable by coga . how do they remember the macro?

**Comment by lseeman** [comment]
Note we will make a list of issues - hopefully over the next few weeks. Hopefully it will be easier then a ton of individual comments

**Comment by RealJoshue108** [comment]
Good to hear this is useful - as we are currently getting welcome feedback from COGA - closing issue.
