### ISSUE TITLE
Split input and output user needs to simplify I/O requirements [NAUR]

### ISSUE THREAD

**Issue by JWJPaton** [w3c/apa#152]
By splitting the user needs for input and output we can simplify the section slightly. The below text also allows for designers to use alternative interface methods and could point to the related document/document section to advise them on how to do so.

I suggest changing User needs 6, 7 and 8 with the ones below.

 - **User need 6:** A user is not able to hear spoken feedback either temporarily due to environmental factors or as the result of a long-term impairment.
 - **REQ 6:** Either support natural language output through text **or** an alternative communication method (see WCAG section XXX).

 - **User need 7:** A user is not able to use spoken feedback on its own but can follow it if accompanied with a synchronised transcript.
 - **REQ 7:** Either support natural language output through synchronised speech and text **or** an alternative communication method (see WCAG section XXX).

 - **User Need 8:** A user is unable to provide input via speech either temporarily due to environmental factors or as the result of a long-term impairment.
 - **REQ 8**: Either support natural language input through text **or** an alternative communication method (see WCAG section XXX).
 
May need to refer to RQTF discussion on the meanings of transcript/captions etc. The word impairment also carries political baggage so may need replacing.

**Comment by jasonjgw** [comment]
I created a naur-input-output branch that attempts such a simplification (not exactly as suggested here, due to the overlap with other requirements, but I hope it divides up and explains the various special cases better).

**Comment by RealJoshue108** [comment]
@jasonjgw I've review this branch, and think it is a worthwhile clarification and worthy of merging.  @JWJPaton while not exactly as you suggested - I think Jasons suggestion goes in the right direction. We can discussion
