### ISSUE TITLE
Consider adding a Summary and Recommendations section to Synchronization Accessibility User Requirements

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#194]
Janina and I discussed this document today. The tentative conclusion was that we should consider adding a "summary and recommendations" section, organized according to whether the multimedia content is live or prerecorded. The recommendations are likely to differ somewhat between those two cases. We also discussed investigating the methods used in some of the published research to understand what kinds of media were involved (e.g., recorded or live broadcast television).

**Comment by RealJoshue108** [comment]
Relates to #248

**Comment by RealJoshue108** [comment]
Discussed at RQTF meeting https://www.w3.org/2021/12/08-rqtf-minutes.html  can be closed
