### ISSUE TITLE
Convert the bibliography to W3C style.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#196]
The bibliography needs to be converted to use SpecRef.

**Comment by Steve-Noble** [comment]
I thought that SpecRef applied to technical specifications and similar documents, as opposed to journal articles which is the vats majority of what we include in our bibliography. I note that [COGA utilized a "biblio.js" file format](https://github.com/w3c/coga/blob/main/common/biblio.js) for their bibliography. However, this format may be over enthusiastic for our purposes, but this can be further discussed.

**Comment by Steve-Noble** [comment]
Thanks, Jason. I understand now that you mean to create a biblio.js file. If you could do this, that would be great. Otherwise I will try to figure out how to do this.

**Comment by RealJoshue108** [comment]
Discussed at RQTF meeting https://www.w3.org/2021/12/08-rqtf-minutes.html  can be closed
