### ISSUE TITLE
We should take into account the audio/video synchronization recommendations in section 6.5.4 of EN 301 549.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#219]
Section 6.5.4 of EN 301 549 v3.2.1 sets a limit of 100ms for the synchronization of audio and video in real-time communication. There is also a note stating that research findings show comprehension is worse if the audio track is ahead of the video.

We should note these recommendations in our document and respond appropriately.

**Comment by RealJoshue108** [comment]
@jasonjgw do you want to have a crack at that in the document?
