### ISSUE TITLE
Consider citing Intelligent Personal Assistant Architecture draft as useful background

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#220]
Intelligent Personal Assistant Architecture is n editors' draft that proposes an architecture for such systems suitable for subsequent standardization.
https://w3c.github.io/voiceinteraction/voice%20interaction%20drafts/paArchitecture-1-2.htm

We should consider citing it as relevant background to natural language interfaces (speech-based and otherwise).

**Comment by RealJoshue108** [comment]
@jasonjgw Good suggestion - is there a particular section you had in mind for the reference?

**Comment by jasonjgw** [comment]
I think the entire document constitutes valuable background and should simply be cited as is.

**Comment by jasonjgw** [comment]
I drafted text and a reference. I'm not sure whether it's in the right place, and it could be improved. I would suggest reviewing, editing as appropriate, and merging.
