### ISSUE TITLE
[SAUR] Consider BBC White Paper 259 for subtitle latency vs accuracy perception

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/apa#228]
BBC R&D paper https://www.bbc.co.uk/rd/publications/whitepaper259 experimentally assesses the relative perception of accuracy vs latency for subtitles, which is especially pertinent to the live subtitle discussion. I'd suggest considering referencing it.

**Comment by RealJoshue108** [comment]
@nigelmegitt I think this is very useful addition - I've added it to the section on Caption rate, as an Editors note.  https://raw.githack.com/w3c/apa/main/saur/index.html @jasonjgw

**Comment by nigelmegitt** [comment]
Thanks @RealJoshue108 - I am sure there are a great many research questions that haven't been either asked well, or studied, in this area.

**Comment by RealJoshue108** [comment]
There sure are - any other items that you'd like to discuss do ping, post issues or join calls. Interestingly, the conclusion of this paper is that:

>It is clear from these results that for the section of the population with hearing difficulties who use
subtitles alongside sound to watch television, any reduction in the delay of subtitles can provide a
useful improvement to the quality of their viewing experience

And I think this is interesting, as it may be dependent also on the context, or purpose of the show / program the user is watching. I find myself wondering about the contexts where tolerances/delays are useful and others where they may not be.

**Comment by RealJoshue108** [comment]
Discussed at RQTF meeting https://www.w3.org/2021/12/08-rqtf-minutes.html  can be closed

**Comment by nigelmegitt** [comment]
That link to minutes gives me a 404 @RealJoshue108 . Is it public-visible?

**Comment by jasonjgw** [comment]
This should now be fixed, as the meeting has just ended and the minutes were generated.

**Comment by nigelmegitt** [comment]
Thanks, I can see it now.
