### ISSUE TITLE
SAUR Subtitle/Caption synchronisation

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/apa#248]
Whilst there is currently consideration of rate of captions (i.e. reading speed required) and latency of live created captions, there is not yet any consideration of the synchronisation thresholds for authors and user agents for prepared captions.

It's [typical practice](https://bbc.github.io/subtitle-guidelines/#Matching-shots) to author (non-live) subtitles with frame accuracy at a production frame rate of 24 or 25 fps, taking into account shot changes.  It is important that user agents presenting those captions/subtitles get somewhat close to meeting that authoring practice. I would suggest that the user agent should present subtitles within +/- 20ms of the authored time, as a useful starting point. It would be helpful to document this.

In the case where lower frame rate videos are created for distribution on low data rate networks, the user agent needs to try to match the timing as referenced by the _audio_ rather than the video. User agents that quantise caption presentation times against video frames are likely to cause significant changes to the required reading rate. This is explored in more detail in [EBU Tech3380 (PDF)](https://tech.ebu.ch/docs/tech/tech3380.pdf) Annex E.

**Comment by Steve-Noble** [comment]
Thank you, Nigel. I think this is a reasonable suggestion and that providing some guidance for media producers and user agents would be a valuable addition to the document.
