### ISSUE TITLE
More detail on considerations of cognitive complexity as tools and larger platforms that integrate remote meetings are considered

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#253]
This issue was raised at the TPAC 2021 session.

**Comment by jasonjgw** [comment]
It isn't clear what changes would be appropriate to resolve this issue, or where to insert them in the document.

**Comment by sehollier** [comment]
As I understand it from TPAC, This was mainly about platforms like conference platforms that have embedded remote meeting software. The issue seems to be when there is lots of information around the meeting platform which complicates the interface and so the recommendation is to make sure the entire interface is simplified.

**Comment by jasonjgw** [comment]
Perhaps this should be an additional point under section 3.4. I'm not sure how to write it, though, since there are different kinds of complexity and users have diverse needs.

For example, suppose a meeting application is included in educational software. Would it be useful to have only the meeting controls (including control of any presentations or documents involved) presented, excluding everything else, with a button to return to the interface of the learning application? I can imagine this would be helpful to some users and potentially confusing to others.

**Comment by sehollier** [comment]
Perhaps just having the ability to toggle a simplified interface is enough for guidance.

**Comment by sehollier** [comment]
added additional bullet in 3.4: 

Provide suport for the user to toggle between the standard remote meeting interface and a simplified user interface. This would be particularly useful for people with cognitive disabilities.
