### ISSUE TITLE
guidance recommending that remote meeting platforms allow the freezing of client side screen sharing so that users can zoom in without slide changing or rapid motion, then ability to catch up to present time.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#256]
This issue was taken from the TPAC 2021 minutes.

**Comment by RealJoshue108** [comment]
This sounds like a really interesting user need - am interested in discussing the mechanics of related requirements.

**Comment by sehollier** [comment]
Agree. Good to discuss on a RQTF call.

**Comment by RealJoshue108** [comment]
Great - it seems like a useful requirement

**Comment by sehollier** [comment]
Difficulties in implementation and would be difficult ot catch up to real-time interactions. Not to be included at this time.
