### ISSUE TITLE
What should we say about "screen sharing" in remote meetings?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#260]
Several issues have been raised about "screen sharing" in remote meetings.
This is problematic in that it is inherently inaccessible to non-visual users. As I understand it, the technique is implemented by transferring rasterized graphics data from the person who is sharing to other meeting participants. No accessibility API data are transferred. As rasterized images are used, the graphics are not vectors, hence not intrinsically scalable without reducing quality.
What guidance should we give?

**Comment by RealJoshue108** [comment]
We may need to separate the question of the act of 'screen sharing' from 'what is being shared' - as they are two separate things. But taking that this relates to 'what is being shared' - do the usual accessibility best practices not apply here?

**Comment by sehollier** [comment]
I agree in principle, but I'm also aware of products like this: 

https://www.youtube.com/watch?v=36NgkpctW6k

So if I'm understanding it correctly, there's some sort of OCR that goes on depending on what type of content is being shared. This may change the guidance depending on what type of content is being shared. 

Scott.

**Comment by RealJoshue108** [comment]
The API issue is very interesting - I wonder if there is a need for a 'remote meetings API bridge' that supports interoperability and synchronization requirements for alternate content etc?

**Comment by sehollier** [comment]
As discussed in RQTF, since these 3rd party tools are not well developed, we may just want to close this issue
