### ISSUE TITLE
Accessibility of Remote Meetings - Needs of deaf and hard of hearing users

### ISSUE THREAD

**Issue by anormand** [w3c/apa#261]
I think that the Accessibility of Remote Meetings document could include more information about the needs of Deaf and hard of hearing users.

Remote meetings have changed the way that we think about captions, particularly auto-generated captions.

[W3C information on captions](https://www.w3.org/WAI/media/av/captions/) currently states that "Automatically-generated captions do not meet user needs or accessibility requirements, unless they are confirmed to be fully accurate."

But when it comes to remote meetings, user needs for accuracy have to be weighed against user needs for captioning on demand. In other words, accessibility is not a binary choice between 99% accurate live remote captioning and not having captioning. Sometimes users decide that captioning with with a higher percentage of errors is better than no captioning, particularly when it comes to ad hoc meetings. As one staff member told me, "I often get invited to a meeting on hour before it commences, there is no preparation time or make arrangements".

Use cases for auto-captioning include:
- users with mild hearing loss;
- users accessing audio-visual content in noisy or quiet environments;
- users who have English as a second language; and
- users who are passively monitoring conference content, whilst undertaking other tasks.

Auto-captioning can also be beneficial when other participants turn on captioning, because seeing their own words misinterpreted makes people slow down and speak more clearly.

Live remote captioning suits situations where meetings or webinars are scheduled well in advance and users require a high degree of accuracy:
- a student attending a lecture or tutorial;
- someone applying for a job;
- a progress review with a supervisor;
- meeting with a student or any other important meeting.

AI Media has some good information about the [choice between computer generated and human generated captions](https://www.ai-media.tv/should-you-use-computer-generated-or-human-generated-captions/).

I believe that the Accessibility of Remote Meetings document should:
1.  Include more information about the needs of deaf and hard of hearing users.
2. Acknowledge the usefulness of auto-generated captions in some situations.
3. Emphasize that auto-generated captions will not meet the needs of many users.
4. Section 3.1, should state that persons procuring or selecting a platform should:
  - Ensure that the platform provides or supports auto-captioning.
  - Ensure that the platform supports the integration of 3rd party captioning.
  - Note: Disabiltiy:IN has some useful information on [Purchasing and Licensing Accessible Video Conferencing Platforms that Work for Everyone](https://disabilityin.org/resource/purchasing-and-licensing-accessible-video-conferencing-platforms-that-work-for-everyone/).
5. Section 5.1 should advise hosts to:
  - Distribute documents ahead of time so that users can:
    - Get an overview of the topics to be covered ahead of time.
    - Learn new words and names.
    - Follow the presentation on their local device.
  - Remind meeting participants to mute their audio when not in use.
  - Ensure that only one person speaks at a time.
  - Describe what they are seeing on screen and what slide they are up to.

Other than that, the document looks good.

Regards

Andrew Normand
Web Accessibility Lead
The University of Melbourne
Australia
anormand@unimelb.edu.au

**Comment by sehollier** [comment]
I agree with Andrew's comment: automated captions can be useful if available, particularly if they are supported by other visual content such as slides and/or screen sharing to provide additional context. 
Scott.

**Comment by sehollier** [comment]
Discussed in RQTF that automated captions are better than no captions but human captions are better for accuracy. Will add to document.

**Comment by sehollier** [comment]
expanded caption requirement in section 5.1 with the following: 


If a professional captioning service is not available,, enable automated captions. If automated captions are not available in the remote meeting software, consider enabling automated captions in presentation software then share the screen.
