### ISSUE TITLE
COGA TF feedback on Remote Meetings draft - cognitive accessibility considerations still need to be incorporated 

### ISSUE THREAD

**Issue by rainbreaw** [w3c/apa#264]
COGA TF feels that there are significant gaps for cognitive accessibility in the current draft. We have prepared a document as an initial review, but would like to request setting up a joint meeting with the Remote Meetings subgroup in January, 2022. 

Our full initial review is available in this Google Doc: [Summary of COGA TF feedback on Remote Meetings working draft](https://docs.google.com/document/d/1SmQFRTb24YDMkVpb9Bb-NJ_QD-YJ_zfVpqGL50lr9j4/edit?pli=1#). A plain text version of this document is also available:
[COGA TF_ Summary of feedback for Remote Meetings working draft.txt](https://github.com/w3c/apa/files/7696385/COGA.TF_.Summary.of.feedback.for.Remote.Meetings.working.draft.txt).

**Comment by sehollier** [comment]
All issues are now filed separately with remote meeting label.  Closing Issue

**Comment by rainbreaw** [comment]
Not reopening, just adding the list of issue #s here for reference: #292, #291, #290, #289, #288, #287, #286, #285, #284, #283.

The COGA Task Force is reviewing the published TR and will have some follow up comments related to the issues above for consideration for v2.
