### ISSUE TITLE
Intersection Observer review

### ISSUE THREAD

**Issue by LJWatson** [w3c/apa#3]
The WebPlat WG has just published the FPWD of [Intersection Observer](https://www.w3.org/TR/intersection-observer/), triggering wide review. Thanks to its time in incubation, the spec already has good interop, so we're hopeful of moving to CR reasonably quickly.

We don't think this specification affects the UI, but would welcome a second opinion from the APA WG if possible. Feedback no later than Friday 27th October would be appreciated, feedback earlier even more so.

Please file issues on the [Intersection Observer repo](https://github.com/w3c/intersectionobserver/issues/new). 

If this request is better made through another channel, please let me know. Thank you.

**Comment by michael-n-cooper** [comment]
Thanks for the opportunity to review; APA has no comments.
