### ISSUE TITLE
How should we address the Editor's Note on automatic speech recognition for captions?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#301]
The Editor's Note in section 2.2.2 (Captions for Live Media) reads as follows.

"The Task Force plans to provide here a more adequate characterization of the trade-off between caption latency and the accuracy of automatic speech recognition systems, compared with that of human transcription. Review and comments on this point are invited.

The Task Force is also aware of recent decisions by the U.S. Federal Communications Commission granting conditional certification for ASR generated captions in Internet telephony. See [fcc-auto-speech] for the legal background to these decisions. This and similar research or regulatory activities will be of interest for subsequent drafts of this document."

What further changes to the document should be made to address this issue? If we proceed to a second Public Working Draft, should we leave the Editor's Note in place to seek further review? (The Note could be updated to take account of any revisions that we decide to make in response to the issue.)

**Comment by Steve-Noble** [comment]
I would suggest that this note was addressed when we added text to address https://github.com/w3c/apa/issues/229 
Therefore, we could simply remove the editor's note. However, if you feel we need to add additional text to be more deliberate, that would be fine as well.

**Comment by jasonjgw** [comment]
I agree with Steve's comment. If we think the text is otherwise appropriate, we could perhaps simply add a non-editorial note on the FCC's stance regarding the use of ASR in caption creation.

**Comment by jasonjgw** [comment]
I have created Pull Request #302, which moves the reference to the series of FCC decisions to a non-editorial note in place of the Editor's Note. Improvements and comments are of course welcome. This is a minimal change that may, or may not be deemed sufficient.
