### ISSUE TITLE
Harmonise reference/link to WalkinVRDRiver

### ISSUE THREAD

**Issue by matatk** [w3c/apa#47]
The link to WalkinVRDriver in [section 3](https://raw.githack.com/w3c/apa/38a0617945cdd79579be632add45e78d0b78e39c/xaur/index.html#understanding-xr-and-accessibility-challenges) differs to the one in [section 3.5](https://raw.githack.com/w3c/apa/38a0617945cdd79579be632add45e78d0b78e39c/xaur/index.html#xr-controller-challenges)—suggest the name and link from §3.5 be used in both cases.

**This needs to have the XAUR label, but I don't have permissions to make that change on this repo.** 

*[Original feedback email, for reference](https://lists.w3.org/Archives/Public/public-apa-admin/2020Jan/0021.html)*

**Comment by joshueoconnor** [comment]
Thanks @matatk this is fixed in current draft https://www.w3.org/TR/xaur/#understanding-xr-and-accessibility-challenges

**Comment by RealJoshue108** [comment]
Thanks @matatk this is fixed in current draft https://www.w3.org/TR/xaur/#understanding-xr-and-accessibility-challenges. This can be closed.
