### ISSUE TITLE
AbleGamers reference

### ISSUE THREAD

**Issue by matatk** [w3c/apa#48]
I realise it may just be a character limit in the footnote IDs, but is it possible to call the "able-game" footnote ID (used in [section 3](https://raw.githack.com/w3c/apa/38a0617945cdd79579be632add45e78d0b78e39c/xaur/index.html#understanding-xr-and-accessibility-challenges)) "able-gamers" as that's their full name?

**This needs to have the XAUR label, but I don't have permissions to make that change on this repo.** 

*[Original feedback email, for reference](https://lists.w3.org/Archives/Public/public-apa-admin/2020Jan/0021.html)*

**Comment by RealJoshue108** [comment]
Thanks @matatk this is fixed in current draft https://www.w3.org/TR/xaur/. This can be closed.
