### ISSUE TITLE
Copy note/list clarification

### ISSUE THREAD

**Issue by matatk** [w3c/apa#49]
In [section 3.2](https://raw.githack.com/w3c/apa/38a0617945cdd79579be632add45e78d0b78e39c/xaur/index.html#xr-and-supporting-multimodality) it says "There will be many modality aspects for the developer and/or content author to consider:" - it looks like there's going to be a list of things there, but a "NOTE:". (The section ends by saying what's coming up in the input section, so I'm not sure if the colon relates to "the following sections".)

**This needs to have the XAUR label, but I don't have permissions to make that change on this repo.** 

*[Original feedback email, for reference](https://lists.w3.org/Archives/Public/public-apa-admin/2020Jan/0021.html)*

**Comment by RealJoshue108** [comment]
This has been fixed in the current draft https://www.w3.org/TR/xaur/#xr-and-supporting-multimodality. This can be closed.
