### ISSUE TITLE
REQ 3a: Symbol sets too specific?

### ISSUE THREAD

**Issue by cdpatnoe** [w3c/apa#69]
I'm wonder if this is really representative of the need and solution. When I read "symbol sets" I think unicode. When I think of AAC, I think of pictures, and they're not the same.  

Can we be less specific

**Comment by RealJoshue108** [comment]
Thanks @cdpatnoe - I will discuss with members of Cognitive and Learning Disabilities Accessibility Task Force (COGA) on approaches to the language - interesting catch.

**Comment by RealJoshue108** [comment]
Just for the record, this is the relevant part of the note https://www.w3.org/TR/xaur/#immersive-personalisation

**Comment by SteveALee** [comment]
@cdpatnoe That's a really interesting point and I think exposes the fact that different domains use the term 'Symbol' for different purposes. Plus there are closely related terms like glyphs, symbols, pictograms images, emojis, emoticons, pictures and even photos or sprites that are all fairly loosely defined and freely used.

Plus the use overlaps as the glyphs in unicode now include pictograms and emojis.

For anyone who has or is working with people with language difficulties the term Symbol Set is the correct one for collections of images use to aid communication. At least in the UK. Some other countries call them Pictograms. They are used manually as a printout or in electronic Assistive Technology usually termed AAC (Alternative and Augmentative Communication). In an ACC the idea is to build up messages by selecting symbols and which is then spoke by the device .

Here's some [symbol sets](https://www.opensymbols.org/) and a web [aac](https://www.mycoughdrop.com/example/core-24-do)  

So in the context of User Need 3 "Symbol Sets" makes sense. However I understand that the target audience of this document may make differing associations, as you point out.

I'll discuss this with the task force.

**Comment by SteveALee** [comment]
ps @cdpatnoe I included more general background in my response so others not aware of AAC might pick up the thread. Hope you didn't mind.

**Comment by cdpatnoe** [comment]
Not a bit, let's be inclusive to do it right :)

**Comment by SteveALee** [comment]
:) What's interesting is that the use for AAC can potentially use any source of images for Symbols Sets - even unicode glyphs! (now I need to lie down and rest - LOL)

**Comment by RealJoshue108** [comment]
Thanks for raising this @cdpatnoe. It looks like the consensus is to leave the language as it is. So I'm going to close this issue. If you are not happy and want to re-open let me know, and we an discuss further.
