### ISSUE TITLE
Visual and audio guidelines

### ISSUE THREAD

**Issue by ajay-sh21** [w3c/apa#79]
There should be some easy way to navigate in the environment for people with different abilities for example, visible glowing lines that would guide the users to their destinations, and these guidelines could be made audible based on their spatial position.

**Comment by RealJoshue108** [comment]
This highlights the issue for multi-modal navigational affordances. Relates to Marking objects as important #78 and duplicates some points there.

**Comment by ajay-sh21** [comment]
I assume guidelines could be implemented if object could be identified programmatically.

**Comment by RealJoshue108** [comment]
@ajay-sh21 Yes, and then logical affordances can be built from the ability for a user agent to identify objects etc.
