### ISSUE TITLE
4.13 Immersive time limits

### ISSUE THREAD

**Issue by nicolocarpignoli** [w3c/apa#84]
On REQ 12a, users may benefit on having an option to enable/disable a clock always shown, e.g. on top of the screen/bottom of the screen, to not lost track of time.

They could also benefit on having an option to display time passed from the start of the current VR/AR session. This way they can control time spent on VR/AR without having an alarm set on a pre-defined time limit - as proposed on REQ 12, that may not be liked by everybody. A limit and an alarm may cause anxiety on some users. 

They should be able to decide between to always have an eye on spent time, or to set a time limit (plus an alarm, eventually).

**Comment by RealJoshue108** [comment]
@nicolocarpignoli Yes, you are right about the alarm - as customisation of the mechanism used to track time. Good stuff.

**Comment by RealJoshue108** [comment]
@nicolocarpignoli We discussed this in RQTF - and the consensus was that this is rather a generic requirement and may be covered by some degree by WCAG Timing Adjustable SC https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html  

However, I'm thinking there may be a new technique for this for Silver or WCAG 2.2, around how to manage a timelimit - but again this could be a rather generic requirement of benefit for all users and not just an accessibility issue.

https://www.w3.org/WAI/WCAG21/Techniques/general/G198

**Comment by RealJoshue108** [comment]
RQTF minutes: https://www.w3.org/2020/04/29-rqtf-minutes.html

**Comment by nicolocarpignoli** [comment]
I reviewed last draft of XAUR (26th August). Okay to me, I think we can close this issue.

**Comment by RealJoshue108** [comment]
Thanks @nicolocarpignoli
