### ISSUE TITLE
4.16 Interaction speed

### ISSUE THREAD

**Issue by nicolocarpignoli** [w3c/apa#85]
REQ 15c
To have an avatar it's a good idea and I think it's something that is starting to raise from different needs (see REQ 10a). Maybe an idea is to have THE SAME avatar to help in different situations and to guide the user on customisation settings of the VR/AR platform/app.

The avatar should be customisable itself, to make the user comfortable and feel friendly.

**Comment by RealJoshue108** [comment]
@nicolocarpignoli yes, the idea of a personalised or customised avatar for this purposes is good. It is implied in the text but we will discuss in RQTF if it should be more explicit.

**Comment by RealJoshue108** [comment]
@nicolocarpignoli it looks like we never actually got around to discussing this in detail in Research Questions but on looking at the new draft of XAUR (which I'm currently working on) - I do think new personalisation and customisation references may cover this sufficiently. 

We can for sure discuss further but I suggest you review the new draft, when we publish and comment.

**Comment by nicolocarpignoli** [comment]
I look into it (26th August version) and although I do not see an explicit mention to the 'angel' personalisation, I do think that these details can be seen as included into W3C related personalisation works (i'm talking about the NOTE on 4.3)

**Comment by RealJoshue108** [comment]
Sounds reasonable, and I also agree. Will close @nicolocarpignoli
