### ISSUE TITLE
In a video conference session in which sign language interpretation is provided, both the signer and the speaker should be visible

### ISSUE THREAD

**Issue by jasonjgw** [w3c/apa#97]
A use case and, if appropriate, a requirement should be added regarding the user's ability to ensure that both a sign language interpreter and the person speaking (whose speech is being interpreted) are simultaneously visible. Anchoring specific meeting participants to specific windows is one means of meeting this objective.

**Comment by RealJoshue108** [comment]
This was discussed in RQTF on 22/6/2020 https://www.w3.org/2020/07/22-rqtf-minutes.html#item01

**Comment by RealJoshue108** [comment]
[New Use Case]: There is a need for a dear or hard of hearing user to 'anchor' certain windows so they can associate the sign language interpreter with the correct speaker so both a sign language interpreter and the person speaking (whose speech is being interpreted) are simultaneously visible.

**Comment by jasonjgw** [comment]
It was noted at the meeting that the user may also wish to ensure the captions are visible in this scenario.
